spring:
  application:  # 应用名字，eureka 会根据它作为服务id
    name: spring-cloud-eureka-provider

    #    链路采集专用
  zipkin:
    base-url: http://localhost:9411
    #设置Sleuth的抽样收集概率
  sleuth:
    sampler:
      probability: 0.1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8701/eureka/,http://localhost:8702/eureka/,http://localhost:8703/eureka/

server:
  port: 8706


