spring:
  application:  # 应用名字，eureka 会根据它作为服务id
    name: spring-cloud-eureka-consumer

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8701/eureka/,http://localhost:8702/eureka/,http://localhost:8703/eureka/

server:
  port: 8712
