server:
  port: 8765
spring:
  application:
    name: oauth2-client
  redis:
    host: 127.0.0.1
    database: 0
security:
  oauth2:
#    resource:
#      user-info-uri: http://localhost:8051/users/current
#    client:
#      id: client_2
#      client-secret: 123456
#      access-token-uri: http://localhost:8051/oauth/token
#      grant-type: client_credentials,password
#      scope: server

    client:
      client-id: client_1
      client-secret: 123456
      user-authorization-uri: http://localhost:8051/oauth/authorize
      access-token-uri: http://localhost:8051/oauth/token
    resource:
#      id: user-client
#      user-info-uri: user-info
      jwt:
        key-uri: http://localhost:8051/oauth/token_key
    authorization:
      check-token-access: http://localhost:8051/oauth/check_token