spring:
  application:  # 应用名字，eureka 会根据它作为服务id
    name: spring-cloud-eureka-server

eureka:
  instance:
    hostname: eureka3
  client:
    serviceUrl:
      defaultZone: http://eureka1:8700/eureka/,http://eureka2:8701/eureka/
server:
  port: 8702


#eureka:
##  client:
###    表示是否将自己注册到Eureka Server，默认为true。
##    registerWithEureka: false
###    表示是否从Eureka Server获取注册信息，默认为true。
##    fetchRegistry: false
#  server:
#    waitTimeInMsWhenSyncEmpty: 0