spring:
  application:  # 应用名字，eureka 会根据它作为服务id
    name: spring-cloud-eureka-server

eureka:
  instance:
    hostname: eureka1
  client:
    serviceUrl:
      defaultZone: http://eureka2:8701/eureka/,http://eureka3:8702/eureka/
#    #    表示是否将自己注册到Eureka Server，默认为true。
#    registerWithEureka: false
#    #    表示是否从Eureka Server获取注册信息，默认为true。
#    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
server:
  port: 8703